version: '3'

services:

  app:
    build: app
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_PORT=${ELASTIC_PORT}
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/8000"
      interval: 5s
      timeout: 3s
      retries: 20
    depends_on:
      elastic:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true

  nginx:
    image: nginx:1.27.0-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/app.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    command: [nginx-debug, '-g', 'daemon off;']
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      - app
