version: '3'

services:

  app:
    build: app
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/8000"
      interval: 5s
      timeout: 3s
      retries: 20
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      migrate:
        condition: service_completed_successfully

  migrate:
    build: app
    command: alembic upgrade head
    restart: on-failure
    env_file:
      - ./.env
    # restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        restart: true

  nginx:
    image: nginx:1.27.0-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/app.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    command: [nginx-debug, '-g', 'daemon off;']
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      - app
